CREATE TABLE "Receipt" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "orderId" INTEGER NOT NULL UNIQUE,
  "orderName" TEXT NOT NULL DEFAULT '',
  "totalTHB" INTEGER NOT NULL,
  "paymentMethod" TEXT NOT NULL,
  "locationLabel" TEXT NOT NULL DEFAULT '',
  "itemsJson" TEXT NOT NULL,
  "confirmedAt" DATETIME NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
